<?php

namespace Database\Seeders;

use App\Models\EmailTemplate;
use App\Models\NotificationProvider;
use App\Models\NotificationSetting;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Str;

class NotificationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->seedEmailTemplates();
        $this->seedNotificationProviders();
        $this->seedNotificationSettings();
    }

    /**
     * Seed default email templates.
     */
    protected function seedEmailTemplates(): void
    {
        $templates = [
            [
                'name' => 'Attendance Check-In Notification',
                'slug' => 'attendance_check_in',
                'subject' => '{{user_name}} has checked in at {{check_in_time}}',
                'body_html' => '<!DOCTYPE html>
<html>
<head>
    <title>Attendance Check-In</title>
</head>
<body>
    <h2>Attendance Check-In Notification</h2>
    <p>Hello {{manager_name}},</p>
    <p>{{user_name}} has checked in at {{check_in_time}} on {{attendance_date}}.</p>
    <p><strong>Status:</strong> {{status}}</p>
    <p><strong>Location:</strong> {{location}}</p>
    {{#if late_minutes}}
    <p><strong>Late by:</strong> {{late_minutes}} minutes</p>
    {{/if}}
    <hr>
    <p>This is an automated notification from the attendance system.</p>
</body>
</html>',
                'body_text' => "Attendance Check-In Notification\n\nHello {{manager_name}},\n\n{{user_name}} has checked in at {{check_in_time}} on {{attendance_date}}.\n\nStatus: {{status}}\nLocation: {{location}}\n{{#if late_minutes}}Late by: {{late_minutes}} minutes\n{{/if}}\n---\nThis is an automated notification from the attendance system.",
                'variables' => json_encode(['user_name', 'check_in_time', 'attendance_date', 'status', 'location', 'manager_name', 'late_minutes']),
                'category' => 'system',
                'locale' => 'en',
                'is_active' => true,
            ],
            [
                'name' => 'Welcome Email',
                'slug' => 'welcome_email',
                'subject' => 'Welcome to {{app_name}}, {{user_name}}!',
                'body_html' => '<!DOCTYPE html>
<html>
<head>
    <title>Welcome</title>
</head>
<body>
    <h2>Welcome to {{app_name}}!</h2>
    <p>Hello {{user_name}},</p>
    <p>Your account has been successfully created.</p>
    <p>You can log in using your email: {{user_email}}</p>
    <p><a href="{{login_url}}">Click here to log in</a></p>
    <p>If you have any questions, please contact us at {{support_email}}.</p>
    <hr>
    <p>Thank you for joining us!</p>
</body>
</html>',
                'body_text' => "Welcome to {{app_name}}!\n\nHello {{user_name}},\n\nYour account has been successfully created.\n\nYou can log in using your email: {{user_email}}\n\nLogin URL: {{login_url}}\n\nIf you have any questions, please contact us at {{support_email}}.\n\nThank you for joining us!",
                'variables' => json_encode(['user_name', 'user_email', 'app_name', 'login_url', 'support_email']),
                'category' => 'system',
                'locale' => 'en',
                'is_active' => true,
            ],
            [
                'name' => 'Report Generated Notification',
                'slug' => 'report_generated',
                'subject' => 'Your {{report_name}} report is ready',
                'body_html' => '<!DOCTYPE html>
<html>
<head>
    <title>Report Generated</title>
</head>
<body>
    <h2>Report Generated</h2>
    <p>Hello {{user_name}},</p>
    <p>Your {{report_name}} report has been generated successfully.</p>
    <p><strong>Generated by:</strong> {{generated_by}}</p>
    <p><strong>Generated at:</strong> {{generated_at}}</p>
    <p><strong>Report type:</strong> {{report_type}}</p>
    <p><strong>File size:</strong> {{file_size}}</p>
    <p><strong>Row count:</strong> {{row_count}}</p>
    <p><strong>Format:</strong> {{format}}</p>
    <p><a href="{{download_url}}">Download Report</a></p>
    <hr>
    <p>This report will be available for 7 days.</p>
</body>
</html>',
                'body_text' => "Report Generated\n\nHello {{user_name}},\n\nYour {{report_name}} report has been generated successfully.\n\nGenerated by: {{generated_by}}\nGenerated at: {{generated_at}}\nReport type: {{report_type}}\nFile size: {{file_size}}\nRow count: {{row_count}}\nFormat: {{format}}\n\nDownload URL: {{download_url}}\n\nThis report will be available for 7 days.",
                'variables' => json_encode(['user_name', 'report_name', 'generated_by', 'generated_at', 'report_type', 'file_size', 'row_count', 'download_url', 'format']),
                'category' => 'system',
                'locale' => 'en',
                'is_active' => true,
            ],
            [
                'name' => 'Report Generated (Admin Notification)',
                'slug' => 'report_generated_admin',
                'subject' => 'Report Generated: {{report_name}} by {{generated_by_user}}',
                'body_html' => '<!DOCTYPE html>
<html>
<head>
    <title>Report Generated - Admin Notification</title>
</head>
<body>
    <h2>Report Generated - Admin Notification</h2>
    <p>Hello {{admin_name}},</p>
    <p>A {{report_name}} report has been generated by {{generated_by_user}} ({{generated_by_email}}).</p>
    <p><strong>Generated at:</strong> {{generated_at}}</p>
    <p><strong>Report type:</strong> {{report_type}}</p>
    <p><strong>File size:</strong> {{file_size}}</p>
    <p><strong>Row count:</strong> {{row_count}}</p>
    <p><strong>Format:</strong> {{format}}</p>
    <hr>
    <p>This is an automated notification for system administrators.</p>
</body>
</html>',
                'body_text' => "Report Generated - Admin Notification\n\nHello {{admin_name}},\n\nA {{report_name}} report has been generated by {{generated_by_user}} ({{generated_by_email}}).\n\nGenerated at: {{generated_at}}\nReport type: {{report_type}}\nFile size: {{file_size}}\nRow count: {{row_count}}\nFormat: {{format}}\n\nThis is an automated notification for system administrators.",
                'variables' => json_encode(['admin_name', 'report_name', 'generated_by_user', 'generated_by_email', 'generated_at', 'report_type', 'file_size', 'row_count', 'format']),
                'category' => 'system',
                'locale' => 'en',
                'is_active' => true,
            ],
            [
                'name' => 'Report Generation Failed',
                'slug' => 'report_generation_failed',
                'subject' => 'Failed to Generate {{report_name}}',
                'body_html' => '<!DOCTYPE html>
<html>
<head>
    <title>Report Generation Failed</title>
</head>
<body>
    <h2>Report Generation Failed</h2>
    <p>Hello {{user_name}},</p>
    <p>We encountered an error while generating your {{report_name}} report.</p>
    <p><strong>Error:</strong> {{error_message}}</p>
    <p><strong>Error Code:</strong> {{error_code}}</p>
    <p><strong>Failed at:</strong> {{failed_at}}</p>
    <hr>
    <p>Please try again or contact support if the issue persists.</p>
    <p>Support Email: {{support_email}}</p>
</body>
</html>',
                'body_text' => "Report Generation Failed\n\nHello {{user_name}},\n\nWe encountered an error while generating your {{report_name}} report.\n\nError: {{error_message}}\nError Code: {{error_code}}\nFailed at: {{failed_at}}\n\nPlease try again or contact support if the issue persists.\nSupport Email: {{support_email}}",
                'variables' => json_encode(['user_name', 'report_name', 'error_message', 'error_code', 'failed_at', 'support_email']),
                'category' => 'system',
                'locale' => 'en',
                'is_active' => true,
            ],
            [
                'name' => 'Report Generation Failed (Admin Notification)',
                'slug' => 'report_generation_failed_admin',
                'subject' => '⚠️ Report Generation Failed: {{report_name}}',
                'body_html' => '<!DOCTYPE html>
<html>
<head>
    <title>Report Generation Failed - Admin Alert</title>
</head>
<body>
    <h2>⚠️ Report Generation Failed - Admin Alert</h2>
    <p>Hello {{admin_name}},</p>
    <p>A report generation has failed and requires attention.</p>
    <p><strong>Report:</strong> {{report_name}}</p>
    <p><strong>Generated by:</strong> {{generated_by}} ({{generated_by_email}})</p>
    <p><strong>Error:</strong> {{error_message}}</p>
    <p><strong>Error Code:</strong> {{error_code}}</p>
    <p><strong>Failed at:</strong> {{failed_at}}</p>
    <p><strong>Priority:</strong> {{priority}}</p>
    <hr>
    <p><strong>Error Details:</strong></p>
    <pre>{{error_details}}</pre>
    <hr>
    <p>This is a high priority notification that requires immediate attention.</p>
</body>
</html>',
                'body_text' => "⚠️ Report Generation Failed - Admin Alert\n\nHello {{admin_name}},\n\nA report generation has failed and requires attention.\n\nReport: {{report_name}}\nGenerated by: {{generated_by}} ({{generated_by_email}})\nError: {{error_message}}\nError Code: {{error_code}}\nFailed at: {{failed_at}}\nPriority: {{priority}}\n\nError Details:\n{{error_details}}\n\nThis is a high priority notification that requires immediate attention.",
                'variables' => json_encode(['admin_name', 'report_name', 'generated_by', 'generated_by_email', 'error_message', 'error_code', 'failed_at', 'priority', 'error_details']),
                'category' => 'system',
                'locale' => 'en',
                'is_active' => true,
            ],
            [
                'name' => 'Scheduled Report Ready',
                'slug' => 'scheduled_report_ready',
                'subject' => '{{schedule_frequency}} {{report_name}} is Ready',
                'body_html' => '<!DOCTYPE html>
<html>
<head>
    <title>Scheduled Report Ready</title>
</head>
<body>
    <h2>Scheduled Report Ready</h2>
    <p>Hello {{recipient_name}},</p>
    <p>Your {{schedule_frequency}} {{report_name}} for {{period}} is ready for download.</p>
    <p><strong>Generated at:</strong> {{generated_at}}</p>
    <p><strong>File size:</strong> {{file_size}}</p>
    <p><strong>Format:</strong> {{format}}</p>
    <p><strong>Period:</strong> {{period}}</p>
    <p><a href="{{download_url}}">Download Report</a></p>
    <hr>
    <p>This is an automated scheduled report delivery.</p>
</body>
</html>',
                'body_text' => "Scheduled Report Ready\n\nHello {{recipient_name}},\n\nYour {{schedule_frequency}} {{report_name}} for {{period}} is ready for download.\n\nGenerated at: {{generated_at}}\nFile size: {{file_size}}\nFormat: {{format}}\nPeriod: {{period}}\n\nDownload URL: {{download_url}}\n\nThis is an automated scheduled report delivery.",
                'variables' => json_encode(['recipient_name', 'schedule_frequency', 'report_name', 'period', 'generated_at', 'file_size', 'format', 'download_url']),
                'category' => 'system',
                'locale' => 'en',
                'is_active' => true,
            ],
            [
                'name' => 'Scheduled Report Delivered',
                'slug' => 'scheduled_report_delivered',
                'subject' => 'Scheduled Report Delivered: {{report_name}}',
                'body_html' => '<!DOCTYPE html>
<html>
<head>
    <title>Scheduled Report Delivered</title>
</head>
<body>
    <h2>Scheduled Report Delivered</h2>
    <p>Hello {{admin_name}},</p>
    <p>A scheduled {{schedule_frequency}} {{report_name}} has been delivered successfully.</p>
    <p><strong>Delivered at:</strong> {{generated_at}}</p>
    <p><strong>Recipient count:</strong> {{recipient_count}}</p>
    <p><strong>File size:</strong> {{file_size}}</p>
    <p><strong>Format:</strong> {{format}}</p>
    <p><strong>Period:</strong> {{period}}</p>
    <hr>
    <p><strong>Delivery Summary:</strong></p>
    <ul>
        {{#each recipients}}
        <li>{{this}}</li>
        {{/each}}
    </ul>
    <hr>
    <p>This is an automated delivery confirmation for system administrators.</p>
</body>
</html>',
                'body_text' => "Scheduled Report Delivered\n\nHello {{admin_name}},\n\nA scheduled {{schedule_frequency}} {{report_name}} has been delivered successfully.\n\nDelivered at: {{generated_at}}\nRecipient count: {{recipient_count}}\nFile size: {{file_size}}\nFormat: {{format}}\nPeriod: {{period}}\n\nDelivery Summary:\n{{#each recipients}}{{this}}\n{{/each}}\n\nThis is an automated delivery confirmation for system administrators.",
                'variables' => json_encode(['admin_name', 'schedule_frequency', 'report_name', 'generated_at', 'recipient_count', 'file_size', 'format', 'period', 'recipients']),
                'category' => 'system',
                'locale' => 'en',
                'is_active' => true,
            ],
        ];

        foreach ($templates as $templateData) {
            $templateData['uuid'] = (string) Str::uuid();
            EmailTemplate::firstOrCreate(
                ['slug' => $templateData['slug']],
                $templateData
            );
        }
    }

    /**
     * Seed default notification providers.
     */
    protected function seedNotificationProviders(): void
    {
        $providers = [
            [
                'channel' => 'email',
                'provider' => 'smtp',
                'name' => 'Default SMTP',
                'is_default' => true,
                'priority' => 1,
                'config' => json_encode([
                    'from_address' => config('mail.from.address', 'noreply@example.com'),
                    'from_name' => config('mail.from.name', 'Notification System'),
                    'host' => config('mail.mailers.smtp.host', 'smtp.mailtrap.io'),
                    'port' => config('mail.mailers.smtp.port', 2525),
                    'encryption' => config('mail.mailers.smtp.encryption', 'tls'),
                ]),
                'is_active' => true,
                'daily_limit' => 1000,
                'monthly_limit' => 30000,
            ],
        ];

        foreach ($providers as $providerData) {
            NotificationProvider::firstOrCreate(
                ['channel' => $providerData['channel'], 'provider' => $providerData['provider']],
                $providerData
            );
        }
    }

    /**
     * Seed default notification settings.
     */
    protected function seedNotificationSettings(): void
    {
        $settings = [
            // System defaults (user_id = null)
            [
                'user_id' => null,
                'notification_type' => 'attendance_check_in',
                'channel' => 'email',
                'is_enabled' => true,
                'preferences' => json_encode(['send_to_manager' => true]),
            ],
            [
                'user_id' => null,
                'notification_type' => 'attendance_check_in',
                'channel' => 'in_app',
                'is_enabled' => true,
                'preferences' => json_encode(['show_popup' => true]),
            ],
            [
                'user_id' => null,
                'notification_type' => 'report_generated',
                'channel' => 'email',
                'is_enabled' => true,
                'preferences' => json_encode(['include_attachment' => true]),
            ],
            [
                'user_id' => null,
                'notification_type' => 'report_generated',
                'channel' => 'in_app',
                'is_enabled' => true,
                'preferences' => json_encode([]),
            ],
            [
                'user_id' => null,
                'notification_type' => 'report_generated_admin',
                'channel' => 'email',
                'is_enabled' => true,
                'preferences' => json_encode(['send_to_all_admins' => true]),
            ],
            [
                'user_id' => null,
                'notification_type' => 'report_generation_failed',
                'channel' => 'email',
                'is_enabled' => true,
                'preferences' => json_encode(['retry_count' => 3]),
            ],
            [
                'user_id' => null,
                'notification_type' => 'report_generation_failed',
                'channel' => 'in_app',
                'is_enabled' => true,
                'preferences' => json_encode([]),
            ],
            [
                'user_id' => null,
                'notification_type' => 'report_generation_failed_admin',
                'channel' => 'email',
                'is_enabled' => true,
                'preferences' => json_encode(['priority' => 'high']),
            ],
            [
                'user_id' => null,
                'notification_type' => 'scheduled_report_ready',
                'channel' => 'email',
                'is_enabled' => true,
                'preferences' => json_encode(['include_download_link' => true]),
            ],
            [
                'user_id' => null,
                'notification_type' => 'scheduled_report_delivered',
                'channel' => 'email',
                'is_enabled' => true,
                'preferences' => json_encode(['include_recipient_list' => true]),
            ],
            [
                'user_id' => null,
                'notification_type' => 'welcome_email',
                'channel' => 'email',
                'is_enabled' => true,
                'preferences' => json_encode([]),
            ],
        ];

        foreach ($settings as $settingData) {
            NotificationSetting::firstOrCreate(
                [
                    'user_id' => $settingData['user_id'],
                    'notification_type' => $settingData['notification_type'],
                    'channel' => $settingData['channel'],
                ],
                $settingData
            );
        }
    }
}
